import type { DebugConfig } from "./types";

export const defaultDebugConfig: DebugConfig = {
  cameraHeight: 6.75,
  cameraDistance: 12,
  cameraLerp: 0.08,
  cameraFramingOffset: 1.25,
  cameraYOffset: 0,
  baseWidth: 7,
  baseDepth: 7,
  slabHeight: 3,
  motionRange: 4.5,
  motionSpeed: 2.1,
  speedRamp: 0.16,
  perfectTolerance: 0.18,
  comboTarget: 8,
  recoveryGrowthMultiplier: 1.15,
  recoverySlowdownFactor: 0.72,
  recoverySlowdownPlacements: 3,
  feedbackAudioEnabled: true,
  feedbackHapticsEnabled: true,
  distractionsEnabled: true,
  distractionMotionSpeed: 1,
  distractionTentacleEnabled: true,
  distractionTentacleStartLevel: 4,
  distractionGorillaEnabled: true,
  distractionGorillaStartLevel: 12,
  distractionTremorEnabled: true,
  distractionUfoEnabled: true,
  distractionUfoStartLevel: 22,
  distractionContrastEnabled: true,
  distractionCloudEnabled: true,
  distractionCloudStartLevel: 32,
  integrityPrecariousThreshold: 0.55,
  integrityUnstableThreshold: 0.9,
  integrityWobbleStrength: 0.22,
  collapseDurationSeconds: 1.4,
  collapseTiltStrength: 0.72,
  collapseCameraPullback: 4.8,
  collapseDropDistance: 2.6,
  performanceQualityPreset: 2,
  performanceAutoQualityEnabled: true,
  performanceFrameBudgetMs: 16.7,
  archivalKeepRecentLevels: 14,
  archivalChunkSize: 5,
  lodNearDistance: 6,
  lodFarDistance: 16,
  maxActiveDebris: 24,
  debrisPoolLimit: 48,
  prebuiltLevels: 5,
  debrisLifetime: 1.35,
  debrisTumbleSpeed: 1,
  placementShakeAmount: 0.22,
  gridVisible: false,
};

export function clampDebugConfig(config: DebugConfig): DebugConfig {
  return {
    cameraHeight: clamp(config.cameraHeight, 4, 20),
    cameraDistance: clamp(config.cameraDistance, 7, 24),
    cameraLerp: clamp(config.cameraLerp, 0.02, 0.25),
    cameraFramingOffset: clamp(config.cameraFramingOffset, -1.5, 4),
    cameraYOffset: clamp(config.cameraYOffset, -6, 6),
    baseWidth: clamp(config.baseWidth, 2, 8),
    baseDepth: clamp(config.baseDepth, 2, 8),
    slabHeight: clamp(config.slabHeight, 1, 5),
    motionRange: clamp(config.motionRange, 1, 10),
    motionSpeed: clamp(config.motionSpeed, 0.4, 5),
    speedRamp: clamp(config.speedRamp, 0, 0.8),
    perfectTolerance: clamp(config.perfectTolerance, 0, 0.5),
    comboTarget: Math.round(clamp(config.comboTarget, 2, 12)),
    recoveryGrowthMultiplier: clamp(config.recoveryGrowthMultiplier, 1, 1.5),
    recoverySlowdownFactor: clamp(config.recoverySlowdownFactor, 0.25, 1),
    recoverySlowdownPlacements: Math.round(clamp(config.recoverySlowdownPlacements, 0, 8)),
    feedbackAudioEnabled: config.feedbackAudioEnabled,
    feedbackHapticsEnabled: config.feedbackHapticsEnabled,
    distractionsEnabled: config.distractionsEnabled,
    distractionMotionSpeed: clamp(config.distractionMotionSpeed, 0.2, 3),
    distractionTentacleEnabled: config.distractionTentacleEnabled,
    distractionTentacleStartLevel: Math.round(clamp(config.distractionTentacleStartLevel, 0, 80)),
    distractionGorillaEnabled: config.distractionGorillaEnabled,
    distractionGorillaStartLevel: Math.round(clamp(config.distractionGorillaStartLevel, 0, 80)),
    distractionTremorEnabled: config.distractionTremorEnabled,
    distractionUfoEnabled: config.distractionUfoEnabled,
    distractionUfoStartLevel: Math.round(clamp(config.distractionUfoStartLevel, 0, 100)),
    distractionContrastEnabled: config.distractionContrastEnabled,
    distractionCloudEnabled: config.distractionCloudEnabled,
    distractionCloudStartLevel: Math.round(clamp(config.distractionCloudStartLevel, 0, 120)),
    integrityPrecariousThreshold: clamp(config.integrityPrecariousThreshold, 0.35, 0.85),
    integrityUnstableThreshold: clamp(
      config.integrityUnstableThreshold,
      Math.max(0.45, clamp(config.integrityPrecariousThreshold, 0.35, 0.85) + 0.05),
      1.2,
    ),
    integrityWobbleStrength: clamp(config.integrityWobbleStrength, 0, 1.5),
    collapseDurationSeconds: clamp(config.collapseDurationSeconds, 0.6, 3),
    collapseTiltStrength: clamp(config.collapseTiltStrength, 0.1, 1.3),
    collapseCameraPullback: clamp(config.collapseCameraPullback, 0, 12),
    collapseDropDistance: clamp(config.collapseDropDistance, 0.5, 8),
    performanceQualityPreset: Math.round(clamp(config.performanceQualityPreset, 0, 2)),
    performanceAutoQualityEnabled: config.performanceAutoQualityEnabled,
    performanceFrameBudgetMs: clamp(config.performanceFrameBudgetMs, 10, 40),
    archivalKeepRecentLevels: Math.round(clamp(config.archivalKeepRecentLevels, 4, 40)),
    archivalChunkSize: Math.round(clamp(config.archivalChunkSize, 2, 16)),
    lodNearDistance: Math.round(clamp(config.lodNearDistance, 2, 24)),
    lodFarDistance: Math.round(
      clamp(config.lodFarDistance, Math.max(4, Math.round(clamp(config.lodNearDistance, 2, 24)) + 2), 48),
    ),
    maxActiveDebris: Math.round(clamp(config.maxActiveDebris, 2, 80)),
    debrisPoolLimit: Math.round(clamp(config.debrisPoolLimit, 0, 120)),
    prebuiltLevels: Math.round(clamp(config.prebuiltLevels, 1, 12)),
    debrisLifetime: clamp(config.debrisLifetime, 0.4, 4),
    debrisTumbleSpeed: clamp(config.debrisTumbleSpeed, 0.2, 3),
    placementShakeAmount: clamp(config.placementShakeAmount, 0, 1.5),
    gridVisible: config.gridVisible,
  };
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}
