import { describe, expect, it } from "vitest";
import { clampDebugConfig, defaultDebugConfig } from "../../src/game/debugConfig";

describe("clampDebugConfig", () => {
  it("preserves values inside the accepted range", () => {
    expect(clampDebugConfig(defaultDebugConfig)).toEqual(defaultDebugConfig);
  });

  it("clamps out-of-range numeric values", () => {
    expect(
      clampDebugConfig({
        cameraHeight: 99,
        cameraDistance: 2,
        cameraLerp: 0.7,
        cameraFramingOffset: 9,
        baseWidth: 12,
        baseDepth: 1,
        slabHeight: 8,
        motionRange: -5,
        motionSpeed: 7,
        speedRamp: 9,
        perfectTolerance: 1,
        comboTarget: 99,
        recoveryGrowthMultiplier: 2,
        recoverySlowdownFactor: 0,
        recoverySlowdownPlacements: 99,
        feedbackAudioEnabled: true,
        feedbackHapticsEnabled: false,
        distractionsEnabled: true,
        distractionMotionSpeed: 99,
        distractionTentacleEnabled: true,
        distractionTentacleStartLevel: -10,
        distractionGorillaEnabled: false,
        distractionGorillaStartLevel: 99,
        distractionTremorEnabled: true,
        distractionUfoEnabled: true,
        distractionUfoStartLevel: -30,
        distractionContrastEnabled: false,
        distractionCloudEnabled: true,
        distractionCloudStartLevel: 999,
        integrityPrecariousThreshold: 0,
        integrityUnstableThreshold: 2,
        integrityWobbleStrength: 99,
        collapseDurationSeconds: 99,
        collapseTiltStrength: 0,
        collapseCameraPullback: 99,
        collapseDropDistance: 0,
        performanceQualityPreset: 99,
        performanceAutoQualityEnabled: false,
        performanceFrameBudgetMs: 3,
        archivalKeepRecentLevels: 2,
        archivalChunkSize: 99,
        lodNearDistance: 0,
        lodFarDistance: 1,
        maxActiveDebris: 999,
        debrisPoolLimit: -1,
        prebuiltLevels: 99,
        debrisLifetime: 0.1,
        debrisTumbleSpeed: -1,
        gridVisible: true,
      }),
    ).toEqual({
      cameraHeight: 20,
      cameraDistance: 7,
      cameraLerp: 0.25,
      cameraFramingOffset: 4,
      baseWidth: 8,
      baseDepth: 2,
      slabHeight: 5,
      motionRange: 1,
      motionSpeed: 5,
      speedRamp: 0.8,
      perfectTolerance: 0.5,
      comboTarget: 12,
      recoveryGrowthMultiplier: 1.5,
      recoverySlowdownFactor: 0.25,
      recoverySlowdownPlacements: 8,
      feedbackAudioEnabled: true,
      feedbackHapticsEnabled: false,
      distractionsEnabled: true,
      distractionMotionSpeed: 3,
      distractionTentacleEnabled: true,
      distractionTentacleStartLevel: 0,
      distractionGorillaEnabled: false,
      distractionGorillaStartLevel: 80,
      distractionTremorEnabled: true,
      distractionUfoEnabled: true,
      distractionUfoStartLevel: 0,
      distractionContrastEnabled: false,
      distractionCloudEnabled: true,
      distractionCloudStartLevel: 120,
      integrityPrecariousThreshold: 0.35,
      integrityUnstableThreshold: 1.2,
      integrityWobbleStrength: 1.5,
      collapseDurationSeconds: 3,
      collapseTiltStrength: 0.1,
      collapseCameraPullback: 12,
      collapseDropDistance: 0.5,
      performanceQualityPreset: 2,
      performanceAutoQualityEnabled: false,
      performanceFrameBudgetMs: 10,
      archivalKeepRecentLevels: 4,
      archivalChunkSize: 16,
      lodNearDistance: 2,
      lodFarDistance: 4,
      maxActiveDebris: 80,
      debrisPoolLimit: 0,
      prebuiltLevels: 12,
      debrisLifetime: 0.4,
      debrisTumbleSpeed: 0.2,
      gridVisible: true,
    });
  });
});
